name: Lint VBA

on:
  push:
    branches:
      - dev
      - main
  pull_request:
jobs:
  test-and-static-analysis:
    name: Test and Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        uses: Vba-actions/lint-vba@v1
        with:
          path: './src'
      - name: Generate the artifacts
        uses: Vba-actions/build-excel-addin@v1
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: Addin.xlam
          retention-days: 7
          if-no-files-found: error
